#!/bin/env python3

import os
import sys
if not os.getcwd() in sys.path:
    sys.path.append(os.getcwd())
from nointro.download import download_daily

TMP = 'tmp'
WORK_FOLDER = os.getenv('WORK_FOLDER', os.getcwd())
SEED_NAME = os.getenv('SEED_NAME', os.path.basename(os.getcwd()))
TMP_DIR = os.path.join(WORK_FOLDER, os.getenv('TMP_FOLDER', 'tmp'))
TMP_NOINTRO = os.path.join(TMP_DIR, SEED_NAME)
TMP_DATS = os.path.join(TMP_NOINTRO, 'dats')
HISTORY = os.path.join(TMP_NOINTRO, 'history')
MAIN_URL = 'http://datomatic.org'

def mktmpdirs():
    os.makedirs(TMP_DIR, exist_ok=True)
    os.makedirs(TMP_NOINTRO, exist_ok=True)
    os.makedirs(TMP_DATS, exist_ok=True)
    os.makedirs(HISTORY, exist_ok=True)


def clean():
    # delete old files
    os.system(f'rm -rf {TMP_NOINTRO}/dats/*')


def main():
    def download_dats():
        download_daily()
    download_dats()

    os.system(f'cd {TMP_DATS} && cp ../*.zip . && unzip -jo \'*.zip\' && rm *.zip')
    os.system(f'cd {TMP_NOINTRO} && mv *.zip {HISTORY}')

    # zip files in TMP_DIR with 7z
    print('Zipping files')
    os.system(f'cd {TMP_DIR} && 7z a -tzip nointro.zip nointro/dats')


if __name__ == '__main__':
    mktmpdirs()
    clean()
    main()
